name = "PkgImages"
uuid = "096f1ff3-26dd-468a-bd94-27cf9706e694"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"

[compat]
MethodAnalysis = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
